project:
  type: website
  output-dir: docs

website:
  title: "Chloe Carlstrom"
  favicon: logo1.png
  navbar:
    logo: logo1.png
    left:
      - about.qmd
      - projects.qmd
      - campus-involvement.qmd
      - resume.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true
    page-layout: full
    anchor-sections: false



