project:
  type: website
  output-dir: docs

website:
  title: "Chloe Carlstrom"
  favicon: images/logo.png
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - extra.qmd
      - resume.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true
    page-layout: full
    anchor-sections: false



