project:
  type: website
  output-dir: docs

website:
  title: "Chloe Carlstrom"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - crafts.qmd
      - resume.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true
    page-layout: full


links: 
    links:
    - text: LinkedIn
      href: https://www.linkedin.com/in/chloe-carlstrom-6a12a3333/
    - text: GitHub
      href: https://github.com/chloecarlstrom
    - text: Email
      href: mailto:chloecarlstrom@ucsb.edu
---


