---
title: "Resume"
format: html
---

[**Click here to download**](resume.pdf)

## Experience
**AMIGOS de las Américas, Panamá** — Project Supervisor <br>
*June 2025 - August 2025* <br>
I will be a facilitating volunteer and homestay program for young adults. I will be planning  activities, providing mentorship and support, as well as assisting with program logistics. This position requires a significant amount of bilingual communication with local community residents

**Young Lab, UCSB EEMB Department** — Research Assistant <br>
*January 2024 - present* <br>
I am working with a PhD student researching the effects of human presence and climate change on mosquito abundance and behavior in the Eastern Sierra Nevada.

**Department of Public Worms, UCSB** — Worm Wrangler <br>
*January 2024 - present* <br>
I help grow produce at the student farm and collect food scraps from campus facilities, working to create a closed-loop food system in the UCSB community

**Adventure Programs, UCSB** — Trip/Class Leader, Shift Lead <br>
*September 2021-March 2022(leadership training), April 2022-present (staff)* <br>
I lead outdoor trips such as backpacking and canoeing, including meal and travel planning, and managing group dynamics. I also work renting out ocean sport equipment.

**Storke Ranch Vernal Pools, Goleta** —Restoration Intern <br>
*June 2023 - August  2023* <br>
I assisted in the restoration of local vernal pools, I  conducted vegetation surveys and monitoring, and learned to identify native and invasive plants.

## Education
**Pontificia Universidad Católica de Chile**
*September 2023 - December 2023* | GPA: 4.0 <br>
I participated in a study abroad program in southern Chile focusing on socio-ecological sustainability. 

**UC Santa Barbara**
*September 2021 - current* | GPA: 3.80 - Honors <br>
I am pursuing a degree in Environmental Studies, B.S.

## Certifications
Youth Mental Health First Aid <br>
Adult First Aid/CPR/AED <br>
Smith Certified Driver <br>
PADI Open Water Scuba Diver <br>

## Awards 
Schmitt Family Foundation Fellowship <br>
Dean’s Honors



